apiVersion: v1
kind: Service
metadata:
  name: service-identity
spec:
  type: NodePort
  ports:
    - name: http
      port: 8082
      nodePort: 31002
  selector:
    app: service-identity

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-identity
  template:
    metadata:
      labels:
        app: service-identity
    spec:
      containers:
        - name: service-identity 
          image: pavelpustovoit/service-identity
          ports:
            - name: http
              containerPort: 8082

---
