apiVersion: v1
kind: Service
metadata:
  name: service-stocks
spec:
  type: NodePort
  ports:
    - name: http
      port: 8083
      nodePort: 31003
  selector:
    app: service-stocks

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-stocks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-stocks
  template:
    metadata:
      labels:
        app: service-stocks
    spec:
      containers:
        - name: service-stocks 
          image: pavelpustovoit/service-stocks
          ports:
            - name: http
              containerPort: 8083

---
